import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"v2026.3.7","description":"","frontmatter":{},"headers":[],"relativePath":"changelog/2026/03/2026.3.7.md","filePath":"changelog/2026/03/2026.3.7.md","lastUpdated":1784358336000}');
const _sfc_main = { name: "changelog/2026/03/2026.3.7.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="v2026-3-7" tabindex="-1">v2026.3.7 <a class="header-anchor" href="#v2026-3-7" aria-label="Permalink to &quot;v2026.3.7&quot;">​</a></h1><p>Data de lançamento: <strong>25 de Março de 2026</strong></p><hr><h2 id="novas-funcionalidades" tabindex="-1">Novas Funcionalidades <a class="header-anchor" href="#novas-funcionalidades" aria-label="Permalink to &quot;Novas Funcionalidades&quot;">​</a></h2><h3 id="encaminhar-mensagens-para-novo-atendimento" tabindex="-1">Encaminhar mensagens para novo atendimento <a class="header-anchor" href="#encaminhar-mensagens-para-novo-atendimento" aria-label="Permalink to &quot;Encaminhar mensagens para novo atendimento&quot;">​</a></h3><p>É possível <strong>encaminhar</strong> uma mensagem do chat (texto ou mídia com URL pública HTTPS) para um <strong>novo contato ou canal</strong>, reutilizando o fluxo de iniciar conversa.</p><h4 id="para-que-serve" tabindex="-1">Para que serve? <a class="header-anchor" href="#para-que-serve" aria-label="Permalink to &quot;Para que serve?&quot;">​</a></h4><ul><li><strong>Agilidade</strong> – Reenvie conteúdo para outro cliente ou canal sem copiar/colar manualmente</li><li><strong>Mídia por URL</strong> – Imagens, vídeos, áudios e documentos são enviados quando há URL HTTPS válida no anexo</li></ul><h4 id="como-usar" tabindex="-1">Como usar? <a class="header-anchor" href="#como-usar" aria-label="Permalink to &quot;Como usar?&quot;">​</a></h4><ol><li>No chat, abra o menu da mensagem (três pontos)</li><li>Selecione <strong>Encaminhar</strong></li><li>Escolha o contato e o canal</li><li>Ao concluir, um <strong>toast</strong> oferece o botão <strong>Ir para conversa</strong> — você permanece no chat atual até optar por abrir o novo atendimento</li></ol><hr><h3 id="mensagem-inicial-tipada-na-api-post-chat-create" tabindex="-1">Mensagem inicial tipada na API <code>POST /chat/create</code> <a class="header-anchor" href="#mensagem-inicial-tipada-na-api-post-chat-create" aria-label="Permalink to &quot;Mensagem inicial tipada na API \`POST /chat/create\`&quot;">​</a></h3><p>O corpo da requisição aceita <code>initialMessage</code> como <strong>string</strong> (texto simples, como antes) ou como <strong>objeto</strong> com tipo e, para mídia, URL HTTPS.</p><h4 id="formato-texto" tabindex="-1">Formato texto <a class="header-anchor" href="#formato-texto" aria-label="Permalink to &quot;Formato texto&quot;">​</a></h4><div class="language-json vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;type&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;text&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;content&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Sua mensagem aqui&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h4 id="formato-midia-ex-encaminhamento" tabindex="-1">Formato mídia (ex.: encaminhamento) <a class="header-anchor" href="#formato-midia-ex-encaminhamento" aria-label="Permalink to &quot;Formato mídia (ex.: encaminhamento)&quot;">​</a></h4><div class="language-json vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;type&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;image&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;content&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;Legenda opcional&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;url&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;https://...&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;name&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;arquivo.jpg&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;mimetype&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;image/jpeg&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><p>Tipos suportados: <code>text</code>, <code>image</code>, <code>video</code>, <code>audio</code>, <code>document</code>. A documentação externa da API foi atualizada com exemplos.</p><hr><h3 id="atendimento-automatico-ao-criar-com-mensagem-inicial" tabindex="-1">Atendimento automático ao criar com mensagem inicial <a class="header-anchor" href="#atendimento-automatico-ao-criar-com-mensagem-inicial" aria-label="Permalink to &quot;Atendimento automático ao criar com mensagem inicial&quot;">​</a></h3><p>Quando há <strong>mensagem inicial</strong> a enviar e o usuário está <strong>autenticado</strong> como agente:</p><ul><li>Chat <strong>pendente</strong> → efeito equivalente a <strong>Atender</strong>: status <code>in_progress</code>, responsável atual, mensagem de sistema e regras de pausa de fluxo quando aplicável (clientes marcados como spam não disparam atendimento automático)</li><li>Chat já <strong>em atendimento</strong> com outro responsável → se você não for colaborador, é adicionado como <strong>colaborador</strong> (sem duplicar se já participar)</li></ul><p>Se <strong>não</strong> houver mensagem inicial, o comportamento de criação do chat permanece o anterior.</p><hr><h2 id="beneficios" tabindex="-1">Benefícios <a class="header-anchor" href="#beneficios" aria-label="Permalink to &quot;Benefícios&quot;">​</a></h2><ul><li>✅ <strong>Encaminhamento integrado ao fluxo de novo atendimento</strong> – Menos cliques e menos erro operacional</li><li>✅ <strong>API flexível</strong> – Texto ou mídia por URL na mesma rota de criação de chat</li><li>✅ <strong>Contexto de atendimento alinhado</strong> – Novo chat já em progresso quando faz sentido, ou você como colaborador</li><li>✅ <strong>UX no encaminhamento</strong> – Você decide quando abrir a nova conversa (toast com ação)</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("changelog/2026/03/2026.3.7.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _2026_3_7 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _2026_3_7 as default
};
