import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"v2025.11.11","description":"","frontmatter":{},"headers":[],"relativePath":"changelog/2025/11/2025.11.11.md","filePath":"changelog/2025/11/2025.11.11.md","lastUpdated":1784358336000}');
const _sfc_main = { name: "changelog/2025/11/2025.11.11.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="v2025-11-11" tabindex="-1">v2025.11.11 <a class="header-anchor" href="#v2025-11-11" aria-label="Permalink to &quot;v2025.11.11&quot;">​</a></h1><p>Data de lançamento: <strong>19 de Novembro de 2025</strong></p><hr><h2 id="nova-funcionalidade" tabindex="-1">Nova Funcionalidade <a class="header-anchor" href="#nova-funcionalidade" aria-label="Permalink to &quot;Nova Funcionalidade&quot;">​</a></h2><h3 id="sugestao-automatica-de-campos-ao-finalizar-atendimento" tabindex="-1">Sugestão Automática de Campos ao Finalizar Atendimento <a class="header-anchor" href="#sugestao-automatica-de-campos-ao-finalizar-atendimento" aria-label="Permalink to &quot;Sugestão Automática de Campos ao Finalizar Atendimento&quot;">​</a></h3><p>A IA analisa a conversa e sugere atualizações para o perfil do cliente.</p><h4 id="como-funciona" tabindex="-1">Como funciona? <a class="header-anchor" href="#como-funciona" aria-label="Permalink to &quot;Como funciona?&quot;">​</a></h4><ol><li><strong>Durante o atendimento</strong>: Cliente menciona dados (email, CPF, endereço...)</li><li><strong>Ao clicar em &quot;Resolver&quot;</strong>: IA analisa a conversa</li><li><strong>Sugestões aparecem</strong>: Card mostra campos para atualizar</li><li><strong>Clique para aplicar</strong>: Aceite ou ignore cada sugestão</li></ol><h4 id="exemplo-de-sugestoes" tabindex="-1">Exemplo de sugestões: <a class="header-anchor" href="#exemplo-de-sugestoes" aria-label="Permalink to &quot;Exemplo de sugestões:&quot;">​</a></h4><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>✨ Campos Sugeridos pela IA</span></span>
<span class="line"><span></span></span>
<span class="line"><span>📧 Email                    🟢 Alta Confiança</span></span>
<span class="line"><span>   (vazio) → joao@email.com    [Aplicar]</span></span>
<span class="line"><span></span></span>
<span class="line"><span>🆔 CPF                      🟡 Média Confiança</span></span>
<span class="line"><span>   (vazio) → 123.456.789-00    [Aplicar]</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h4 id="niveis-de-confianca" tabindex="-1">Níveis de confiança: <a class="header-anchor" href="#niveis-de-confianca" aria-label="Permalink to &quot;Níveis de confiança:&quot;">​</a></h4><table tabindex="0"><thead><tr><th>Nível</th><th>Significado</th></tr></thead><tbody><tr><td>🟢 Alta</td><td>Dado explicitamente mencionado</td></tr><tr><td>🟡 Média</td><td>Dado claramente inferido</td></tr><tr><td>🟠 Baixa</td><td>Dado deduzido do contexto</td></tr></tbody></table><h4 id="campos-detectaveis" tabindex="-1">Campos detectáveis: <a class="header-anchor" href="#campos-detectaveis" aria-label="Permalink to &quot;Campos detectáveis:&quot;">​</a></h4><ul><li>Email, Telefone, CPF/CNPJ</li><li>Data de Nascimento, Nome Completo</li><li>Endereço completo</li><li>Empresa, Cargo, Site</li><li>Preferências, Observações</li></ul><h4 id="como-desabilitar" tabindex="-1">Como desabilitar? <a class="header-anchor" href="#como-desabilitar" aria-label="Permalink to &quot;Como desabilitar?&quot;">​</a></h4><ol><li><strong>Configurações</strong> → aba <strong>Organização</strong></li><li>Ative <strong>&quot;Desabilitar Sugestões de Campos na Resolução&quot;</strong></li></ol><hr><h2 id="beneficios" tabindex="-1">Benefícios <a class="header-anchor" href="#beneficios" aria-label="Permalink to &quot;Benefícios&quot;">​</a></h2><ul><li>✅ Cadastros mais completos automaticamente</li><li>✅ Sem esforço extra do atendente</li><li>✅ Reduz erros e omissões</li><li>✅ Melhora gestão de informações</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("changelog/2025/11/2025.11.11.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _2025_11_11 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _2025_11_11 as default
};
