import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"v2025.12.4","description":"","frontmatter":{},"headers":[],"relativePath":"changelog/2025/12/2025.12.4.md","filePath":"changelog/2025/12/2025.12.4.md","lastUpdated":1784358336000}');
const _sfc_main = { name: "changelog/2025/12/2025.12.4.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="v2025-12-4" tabindex="-1">v2025.12.4 <a class="header-anchor" href="#v2025-12-4" aria-label="Permalink to &quot;v2025.12.4&quot;">​</a></h1><p>Data de lançamento: <strong>09 de Dezembro de 2025</strong></p><hr><h2 id="novas-funcionalidades" tabindex="-1">Novas Funcionalidades <a class="header-anchor" href="#novas-funcionalidades" aria-label="Permalink to &quot;Novas Funcionalidades&quot;">​</a></h2><h3 id="opcao-para-desabilitar-resumo-automatico-por-ia" tabindex="-1">Opção para Desabilitar Resumo Automático por IA <a class="header-anchor" href="#opcao-para-desabilitar-resumo-automatico-por-ia" aria-label="Permalink to &quot;Opção para Desabilitar Resumo Automático por IA&quot;">​</a></h3><p>Agora você pode escolher finalizar ou transferir atendimentos sem gerar resumo automático, economizando tokens de IA.</p><h4 id="como-configurar" tabindex="-1">Como configurar? <a class="header-anchor" href="#como-configurar" aria-label="Permalink to &quot;Como configurar?&quot;">​</a></h4><ol><li>Acesse <strong>⚙️ Configurações</strong> no menu lateral</li><li>Navegue até a aba <strong>&quot;Geral&quot;</strong></li><li>Localize a seção <strong>&quot;IA e Automação&quot;</strong> (card roxo)</li><li>Ative as opções desejadas: <ul><li><strong>Desabilitar Resumo por IA na Resolução</strong> - Não gera resumo ao finalizar atendimento</li><li><strong>Desabilitar Resumo por IA na Transferência</strong> - Não gera resumo ao transferir/sair</li></ul></li><li>Clique em <strong>&quot;Salvar&quot;</strong></li></ol><div class="tip custom-block"><p class="custom-block-title">Benefício</p><p>Ao desabilitar essas opções, você economiza chamadas de API e tokens de IA. O campo de resumo continua disponível para preenchimento manual.</p></div><hr><h3 id="melhorias-na-agenda-do-android" tabindex="-1">Melhorias na Agenda do Android <a class="header-anchor" href="#melhorias-na-agenda-do-android" aria-label="Permalink to &quot;Melhorias na Agenda do Android&quot;">​</a></h3><p>Aprimoramentos na usabilidade da agenda no aplicativo Android:</p><h4 id="o-que-melhorou" tabindex="-1">O que melhorou? <a class="header-anchor" href="#o-que-melhorou" aria-label="Permalink to &quot;O que melhorou?&quot;">​</a></h4><ul><li><strong>Proteção contra gestos acidentais</strong>: Bloqueio ou confirmação para ações por movimentos do dedo</li><li><strong>Visualização semanal expandida</strong>: Exibição de 6 ou 7 dias por vez</li><li><strong>Semana iniciando no domingo</strong>: Melhor visão geral da semana</li><li><strong>Criação e edição de eventos</strong>: Agora disponível diretamente pelo app Android</li></ul><hr><h2 id="beneficios" tabindex="-1">Benefícios <a class="header-anchor" href="#beneficios" aria-label="Permalink to &quot;Benefícios&quot;">​</a></h2><ul><li>✅ Economia de tokens de IA</li><li>✅ Mais controle sobre gastos</li><li>✅ Melhor experiência mobile</li><li>✅ Maior praticidade no uso da agenda</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("changelog/2025/12/2025.12.4.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _2025_12_4 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _2025_12_4 as default
};
