import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"v2025.11.7","description":"","frontmatter":{},"headers":[],"relativePath":"changelog/2025/11/2025.11.7.md","filePath":"changelog/2025/11/2025.11.7.md","lastUpdated":1784358336000}');
const _sfc_main = { name: "changelog/2025/11/2025.11.7.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="v2025-11-7" tabindex="-1">v2025.11.7 <a class="header-anchor" href="#v2025-11-7" aria-label="Permalink to &quot;v2025.11.7&quot;">​</a></h1><p>Data de lançamento: <strong>13 de Novembro de 2025</strong></p><hr><h2 id="novas-funcionalidades" tabindex="-1">Novas Funcionalidades <a class="header-anchor" href="#novas-funcionalidades" aria-label="Permalink to &quot;Novas Funcionalidades&quot;">​</a></h2><h3 id="busca-de-chats-por-numero-de-telefone" tabindex="-1">Busca de Chats por Número de Telefone <a class="header-anchor" href="#busca-de-chats-por-numero-de-telefone" aria-label="Permalink to &quot;Busca de Chats por Número de Telefone&quot;">​</a></h3><p>Agora é possível encontrar conversas digitando o número de telefone.</p><h4 id="como-usar" tabindex="-1">Como usar? <a class="header-anchor" href="#como-usar" aria-label="Permalink to &quot;Como usar?&quot;">​</a></h4><ol><li>Clique no ícone de lupa 🔍 no cabeçalho</li><li>Selecione a aba <strong>&quot;Chats&quot;</strong></li><li>Digite o número (completo ou parcial)</li><li>Pressione Enter</li></ol><h4 id="exemplos-de-busca" tabindex="-1">Exemplos de busca: <a class="header-anchor" href="#exemplos-de-busca" aria-label="Permalink to &quot;Exemplos de busca:&quot;">​</a></h4><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>5511987654321    (número completo)</span></span>
<span class="line"><span>11987654321      (sem código do país)</span></span>
<span class="line"><span>4321             (últimos dígitos)</span></span>
<span class="line"><span>11987            (DDD + início)</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h4 id="abas-disponiveis" tabindex="-1">Abas disponíveis: <a class="header-anchor" href="#abas-disponiveis" aria-label="Permalink to &quot;Abas disponíveis:&quot;">​</a></h4><table tabindex="0"><thead><tr><th>Aba</th><th>Para que serve</th></tr></thead><tbody><tr><td>Clientes</td><td>Encontrar clientes e iniciar conversa</td></tr><tr><td><strong>Chats</strong> ⭐</td><td>Encontrar conversas existentes (NOVO!)</td></tr><tr><td>Mensagens</td><td>Buscar conteúdo de mensagens</td></tr></tbody></table><hr><h3 id="configurar-aba-padrao-ao-acessar" tabindex="-1">Configurar Aba Padrão ao Acessar <a class="header-anchor" href="#configurar-aba-padrao-ao-acessar" aria-label="Permalink to &quot;Configurar Aba Padrão ao Acessar&quot;">​</a></h3><p>Escolha qual tela abre automaticamente ao fazer login.</p><h4 id="como-configurar-para-voce" tabindex="-1">Como configurar (para você): <a class="header-anchor" href="#como-configurar-para-voce" aria-label="Permalink to &quot;Como configurar (para você):&quot;">​</a></h4><ol><li>Clique no seu <strong>avatar</strong> (canto inferior esquerdo)</li><li>Encontre <strong>&quot;Tela Inicial&quot;</strong></li><li>Escolha o módulo desejado</li><li>Clique em <strong>&quot;Salvar&quot;</strong></li><li>Faça login novamente</li></ol><h4 id="modulos-disponiveis" tabindex="-1">Módulos disponíveis: <a class="header-anchor" href="#modulos-disponiveis" aria-label="Permalink to &quot;Módulos disponíveis:&quot;">​</a></h4><ul><li>🔵 Dashboard</li><li>💚 Conversas</li><li>👥 Clientes</li><li>💜 CRM</li><li>🟠 Agendamentos</li><li>🔴 Médico</li><li>🔷 Tarefas</li><li>💰 Financeiro</li><li>🟡 PDV</li></ul><hr><h2 id="beneficios" tabindex="-1">Benefícios <a class="header-anchor" href="#beneficios" aria-label="Permalink to &quot;Benefícios&quot;">​</a></h2><ul><li>✅ Localização rápida de conversas</li><li>✅ Busca por número parcial</li><li>✅ Acesso direto à área mais usada</li><li>✅ Experiência personalizada</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("changelog/2025/11/2025.11.7.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _2025_11_7 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _2025_11_7 as default
};
