import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"v2026.6.1","description":"","frontmatter":{},"headers":[],"relativePath":"en/changelog/2026/06/2026.6.1.md","filePath":"en/changelog/2026/06/2026.6.1.md","lastUpdated":1784358336000}');
const _sfc_main = { name: "en/changelog/2026/06/2026.6.1.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="v2026-6-1" tabindex="-1">v2026.6.1 <a class="header-anchor" href="#v2026-6-1" aria-label="Permalink to &quot;v2026.6.1&quot;">​</a></h1><p>Release date: <strong>June 8, 2026</strong></p><hr><h2 id="bug-fixes" tabindex="-1">Bug Fixes <a class="header-anchor" href="#bug-fixes" aria-label="Permalink to &quot;Bug Fixes&quot;">​</a></h2><h3 id="whatsapp-official-template-buttons-not-displayed-in-chat" tabindex="-1">WhatsApp Official Template Buttons Not Displayed in Chat <a class="header-anchor" href="#whatsapp-official-template-buttons-not-displayed-in-chat" aria-label="Permalink to &quot;WhatsApp Official Template Buttons Not Displayed in Chat&quot;">​</a></h3><p>Action buttons from WhatsApp Official templates (quick reply, URL, phone) were not being saved to the conversation history when a template message was sent — neither via manual chat send nor bulk campaigns. As a result, when opening the history, the template message appeared with only the text content (HEADER, BODY and FOOTER), but without any buttons.</p><h4 id="what-was-fixed" tabindex="-1">What was fixed? <a class="header-anchor" href="#what-was-fixed" aria-label="Permalink to &quot;What was fixed?&quot;">​</a></h4><ul><li><strong>Manual send via chat</strong>: when sending a template through the template picker modal, the buttons from the <code>BUTTONS</code> component of the Meta-approved template are now extracted and saved in the message <code>metadata</code> field (<code>template_buttons</code>)</li><li><strong>Bulk send (campaigns)</strong>: when processing bulk campaign dispatches with a WhatsApp Official template, the system now looks up the template buttons in the database and includes them in the saved message <code>metadata</code></li><li><strong>Chat rendering</strong>: the message bubble component (<code>MessageBubble</code>) now reads the <code>metadata.template_buttons</code> field and displays the buttons below the template content, using the same visual style as WAHA templates</li></ul><h4 id="what-is-it-for" tabindex="-1">What is it for? <a class="header-anchor" href="#what-is-it-for" aria-label="Permalink to &quot;What is it for?&quot;">​</a></h4><p>When opening any conversation that received a template with buttons (e.g. quick reply options like &quot;Yes&quot; / &quot;No&quot;, or a website link button), the buttons now appear correctly in the history — exactly as they were sent to the recipient.</p><hr><h2 id="benefits" tabindex="-1">Benefits <a class="header-anchor" href="#benefits" aria-label="Permalink to &quot;Benefits&quot;">​</a></h2><ul><li>✅ Template history now accurately reflects what was sent, including all action buttons</li><li>✅ Fix applied to both manual sends and bulk campaign dispatches</li><li>✅ No impact on previous messages — older messages continue to display normally (without buttons, as before)</li><li>✅ Button visual style consistent with existing WAHA templates</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/changelog/2026/06/2026.6.1.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _2026_6_1 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _2026_6_1 as default
};
