import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"v2025.11.10","description":"","frontmatter":{},"headers":[],"relativePath":"en/changelog/2025/11/2025.11.10.md","filePath":"en/changelog/2025/11/2025.11.10.md","lastUpdated":1784358336000}');
const _sfc_main = { name: "en/changelog/2025/11/2025.11.10.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="v2025-11-10" tabindex="-1">v2025.11.10 <a class="header-anchor" href="#v2025-11-10" aria-label="Permalink to &quot;v2025.11.10&quot;">​</a></h1><p>Release date: <strong>November 18, 2025</strong></p><hr><h2 id="new-features" tabindex="-1">New Features <a class="header-anchor" href="#new-features" aria-label="Permalink to &quot;New Features&quot;">​</a></h2><h3 id="registration-field-indicator" tabindex="-1">Registration Field Indicator <a class="header-anchor" href="#registration-field-indicator" aria-label="Permalink to &quot;Registration Field Indicator&quot;">​</a></h3><p>Visual indicator in chat showing which fields are filled and missing.</p><h4 id="how-does-it-work" tabindex="-1">How does it work? <a class="header-anchor" href="#how-does-it-work" aria-label="Permalink to &quot;How does it work?&quot;">​</a></h4><ul><li>📋 Panel appears next to the chat</li><li>✅ Green icon = Filled field</li><li>⚠️ Yellow icon = Missing field</li><li>🔴 Red icon = Required and missing</li></ul><h4 id="benefit" tabindex="-1">Benefit: <a class="header-anchor" href="#benefit" aria-label="Permalink to &quot;Benefit:&quot;">​</a></h4><ul><li>Quickly see what data is missing</li><li>Fill during conversation</li><li>Click to go directly to field</li></ul><hr><h3 id="auto-call-rejection-for-whatsapp" tabindex="-1">Auto Call Rejection for WhatsApp <a class="header-anchor" href="#auto-call-rejection-for-whatsapp" aria-label="Permalink to &quot;Auto Call Rejection for WhatsApp&quot;">​</a></h3><p>Automatically rejects WhatsApp voice calls with configurable message.</p><h4 id="how-to-configure" tabindex="-1">How to configure? <a class="header-anchor" href="#how-to-configure" aria-label="Permalink to &quot;How to configure?&quot;">​</a></h4><ol><li>Go to <strong>Settings</strong> → <strong>Channels</strong></li><li>Select the WhatsApp channel</li><li>Locate <strong>&quot;Auto Call Rejection&quot;</strong></li><li>Enable the option</li><li>Configure rejection message (optional)</li><li>Save</li></ol><h4 id="example-message" tabindex="-1">Example message: <a class="header-anchor" href="#example-message" aria-label="Permalink to &quot;Example message:&quot;">​</a></h4><blockquote><p>&quot;Sorry, we don&#39;t receive calls. Please send a text message and we&#39;ll respond shortly!&quot;</p></blockquote><h4 id="behavior" tabindex="-1">Behavior: <a class="header-anchor" href="#behavior" aria-label="Permalink to &quot;Behavior:&quot;">​</a></h4><ul><li>📵 Call is automatically rejected</li><li>💬 Configured message is sent</li><li>📊 Event logged for reports</li><li>✅ Works for audio and video calls</li></ul><hr><h2 id="benefits" tabindex="-1">Benefits <a class="header-anchor" href="#benefits" aria-label="Permalink to &quot;Benefits&quot;">​</a></h2><ul><li>✅ Complete registrations without effort</li><li>✅ No interrupted calls</li><li>✅ Clear direction for customers</li><li>✅ Focus on text support</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/changelog/2025/11/2025.11.10.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const _2025_11_10 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  _2025_11_10 as default
};
