import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Query API","description":"","frontmatter":{},"headers":[],"relativePath":"en/guide/ai-agents/tools/query-api.md","filePath":"en/guide/ai-agents/tools/query-api.md","lastUpdated":1784359757000}');
const _sfc_main = { name: "en/guide/ai-agents/tools/query-api.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="query-api" tabindex="-1">Query API <a class="header-anchor" href="#query-api" aria-label="Permalink to &quot;Query API&quot;">​</a></h1><p>Lets the AI <strong>query and run operations on an external API</strong> during support (base URL, encrypted authentication, and an allowlist of routes). Each route becomes a tool whose <strong>name is the slug id</strong> (e.g. <code>get_order</code>).</p><p><strong>When to use:</strong></p><ul><li>Look up order status, charges, inventory, or customer data in external systems</li><li>Create/update records via REST API</li><li>Expose only safe endpoints (allowlist), without open web search</li></ul><p><strong>Setup:</strong></p><ol><li>Add the <strong>Query API</strong> action</li><li>Set <strong>Base URL</strong> and auth type (Bearer, header, or query)</li><li>Save the key (<strong>encrypted</strong>, same pattern as Integrations)</li><li>Add routes: <code>id</code> (slug), description, method, path, and parameters — or use <strong>Generate with AI</strong></li><li>Optional: <strong>test each route</strong> on the server before publishing</li></ol><h4 id="generate-routes-with-ai" tabindex="-1">Generate routes with AI <a class="header-anchor" href="#generate-routes-with-ai" aria-label="Permalink to &quot;Generate routes with AI&quot;">​</a></h4><p>When you add a new action (still without routes), the assistant <strong>opens automatically</strong>. You can:</p><ul><li>Describe in natural language what the agent should do</li><li>Provide a <strong>documentation URL</strong> (optional)</li><li>Paste <strong>docs excerpts</strong> or sample calls (<code>curl</code>)</li></ul><p>AI builds <strong>only the routes you need</strong>, plus the action name, description, and slug. Review, adjust, and test before going live.</p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>Example description + curl:</span></span>
<span class="line"><span></span></span>
<span class="line"><span>I want to connect the Stripe API for support.</span></span>
<span class="line"><span>The agent should look up a customer by email and list open invoices.</span></span>
<span class="line"><span></span></span>
<span class="line"><span>curl -X GET &quot;https://api.stripe.com/v1/customers?email=user@email.com&quot; \\</span></span>
<span class="line"><span>  -H &quot;Authorization: Bearer $STRIPE_API_KEY&quot;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><div class="tip custom-block"><p class="custom-block-title">💡 Assistant with web search</p><p><strong>Generate with AI</strong> uses web search <strong>only while configuring</strong>. In live chats the agent only calls the routes you allowed.</p></div><h4 id="test-routes" tabindex="-1">Test routes <a class="header-anchor" href="#test-routes" aria-label="Permalink to &quot;Test routes&quot;">​</a></h4><p>On each route, use <strong>Test route</strong>, fill sample parameters, and run. The test runs on the <strong>server</strong> (the key never goes to the browser). Last-test status shows as OK, Error, or Untested.</p><div class="warning custom-block"><p class="custom-block-title">⚠️ POST / PUT</p><p>Create or update tests may <strong>create real data</strong> in the external system. Testing every route is not required.</p></div><div class="info custom-block"><p class="custom-block-title">⚠️ Secrets</p><p>The key never enters the tool schema or the model’s tool result. In the UI it appears masked (<code>••••</code>).</p></div><p><strong>Example:</strong></p><div class="language-text vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">text</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>👤 Customer: What&#39;s the status of order 12345?</span></span>
<span class="line"><span>🤖 AI: [calls get_order] Your order 12345 is in transit.</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><blockquote><p>Changelog: <a href="/en/changelog/2026/07/2026.7.10">v2026.7.10</a></p></blockquote></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/guide/ai-agents/tools/query-api.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const queryApi = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  queryApi as default
};
