import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Nó: Grupo","description":"","frontmatter":{},"headers":[],"relativePath":"en/guide/flows/nodes/group.md","filePath":"en/guide/flows/nodes/group.md","lastUpdated":1766498875000}');
const _sfc_main = { name: "en/guide/flows/nodes/group.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="no-grupo" tabindex="-1">Nó: Grupo <a class="header-anchor" href="#no-grupo" aria-label="Permalink to &quot;Nó: Grupo&quot;">​</a></h1><p>Agrupa visualmente nós relacionados para melhor organização do fluxo.</p><h2 id="visao-geral" tabindex="-1">Visão Geral <a class="header-anchor" href="#visao-geral" aria-label="Permalink to &quot;Visão Geral&quot;">​</a></h2><p>O nó <strong>Grupo</strong> é um elemento visual que permite agrupar múltiplos nós. Serve apenas para organização - não afeta a execução do fluxo.</p><h2 id="caracteristicas" tabindex="-1">Características <a class="header-anchor" href="#caracteristicas" aria-label="Permalink to &quot;Características&quot;">​</a></h2><ul><li><strong>Apenas visual</strong>: Não altera a lógica do fluxo</li><li><strong>Organizacional</strong>: Ajuda a entender fluxos complexos</li><li><strong>Redimensionável</strong>: Ajuste o tamanho conforme necessário</li><li><strong>Sem conexões</strong>: Não possui handles de entrada/saída</li></ul><h2 id="como-usar" tabindex="-1">Como Usar <a class="header-anchor" href="#como-usar" aria-label="Permalink to &quot;Como Usar&quot;">​</a></h2><ol><li>Arraste o nó <strong>Grupo</strong> para o canvas</li><li>Redimensione para cobrir os nós desejados</li><li>Adicione um nome/label descritivo</li></ol><h2 id="exemplos-de-uso" tabindex="-1">Exemplos de Uso <a class="header-anchor" href="#exemplos-de-uso" aria-label="Permalink to &quot;Exemplos de Uso&quot;">​</a></h2><h3 id="secao-de-qualificacao" tabindex="-1">Seção de Qualificação <a class="header-anchor" href="#secao-de-qualificacao" aria-label="Permalink to &quot;Seção de Qualificação&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>┌─────────────────────────────────────┐</span></span>
<span class="line"><span>│         📋 QUALIFICAÇÃO             │</span></span>
<span class="line"><span>│  ┌───────┐  ┌───────┐  ┌───────┐    │</span></span>
<span class="line"><span>│  │Texto  │→ │Input  │→ │Condição│   │</span></span>
<span class="line"><span>│  └───────┘  └───────┘  └───────┘    │</span></span>
<span class="line"><span>└─────────────────────────────────────┘</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h3 id="fluxo-de-vendas" tabindex="-1">Fluxo de Vendas <a class="header-anchor" href="#fluxo-de-vendas" aria-label="Permalink to &quot;Fluxo de Vendas&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>┌─────────────────────────────────────┐</span></span>
<span class="line"><span>│         💰 FLUXO DE VENDAS          │</span></span>
<span class="line"><span>│                                     │</span></span>
<span class="line"><span>│  [Apresentação] → [Oferta]          │</span></span>
<span class="line"><span>│        ↓                            │</span></span>
<span class="line"><span>│  [Objeções] → [Fechamento]          │</span></span>
<span class="line"><span>│                                     │</span></span>
<span class="line"><span>└─────────────────────────────────────┘</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h3 id="integracoes" tabindex="-1">Integrações <a class="header-anchor" href="#integracoes" aria-label="Permalink to &quot;Integrações&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>┌─────────────────────────────────────┐</span></span>
<span class="line"><span>│         🔌 INTEGRAÇÕES              │</span></span>
<span class="line"><span>│                                     │</span></span>
<span class="line"><span>│  [API CRM] → [API Pagamento]        │</span></span>
<span class="line"><span>│        ↓                            │</span></span>
<span class="line"><span>│  [Webhook Notificação]              │</span></span>
<span class="line"><span>│                                     │</span></span>
<span class="line"><span>└─────────────────────────────────────┘</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="boas-praticas" tabindex="-1">Boas Práticas <a class="header-anchor" href="#boas-praticas" aria-label="Permalink to &quot;Boas Práticas&quot;">​</a></h2><div class="tip custom-block"><p class="custom-block-title">Nomes Descritivos</p><p>Use nomes claros que descrevam a função do grupo.</p></div><div class="tip custom-block"><p class="custom-block-title">Cores</p><p>Se disponível, use cores diferentes para cada tipo de grupo.</p></div><div class="tip custom-block"><p class="custom-block-title">Não Exagere</p><p>Muitos grupos podem poluir a visualização. Use com moderação.</p></div><div class="tip custom-block"><p class="custom-block-title">Documentação</p><p>Grupos ajudam a documentar visualmente a estrutura do fluxo.</p></div><h2 id="quando-usar" tabindex="-1">Quando Usar <a class="header-anchor" href="#quando-usar" aria-label="Permalink to &quot;Quando Usar&quot;">​</a></h2><p>✅ <strong>Use grupos para:</strong></p><ul><li>Separar seções lógicas do fluxo</li><li>Identificar áreas de responsabilidade</li><li>Documentar visualmente</li><li>Facilitar navegação em fluxos grandes</li></ul><p>❌ <strong>Evite grupos para:</strong></p><ul><li>Fluxos simples (poucos nós)</li><li>Agrupar nós não relacionados</li><li>Substituir boa organização de nós</li></ul><h2 id="proximos-passos" tabindex="-1">Próximos Passos <a class="header-anchor" href="#proximos-passos" aria-label="Permalink to &quot;Próximos Passos&quot;">​</a></h2><ul><li><a href="/guide/flows/builder">Construtor de Fluxos</a></li><li><a href="/guide/flows/nodes/">Tipos de Nós</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/guide/flows/nodes/group.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const group = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  group as default
};
