import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Nó: Nota Privada","description":"","frontmatter":{},"headers":[],"relativePath":"en/guide/flows/nodes/private-note.md","filePath":"en/guide/flows/nodes/private-note.md","lastUpdated":1766498875000}');
const _sfc_main = { name: "en/guide/flows/nodes/private-note.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="no-nota-privada" tabindex="-1">Nó: Nota Privada <a class="header-anchor" href="#no-nota-privada" aria-label="Permalink to &quot;Nó: Nota Privada&quot;">​</a></h1><p>Adiciona uma nota privada ao atendimento, visível apenas para a equipe.</p><h2 id="visao-geral" tabindex="-1">Visão Geral <a class="header-anchor" href="#visao-geral" aria-label="Permalink to &quot;Visão Geral&quot;">​</a></h2><p>O nó <strong>Nota Privada</strong> cria uma anotação no atendimento que:</p><ul><li>É visível apenas para atendentes</li><li><strong>Não é enviada</strong> ao cliente</li><li>Pode ser fixada para destaque</li><li>Aparece como nota/observação no atendimento</li></ul><h2 id="configuracoes" tabindex="-1">Configurações <a class="header-anchor" href="#configuracoes" aria-label="Permalink to &quot;Configurações&quot;">​</a></h2><h3 id="texto-da-nota" tabindex="-1">Texto da Nota <a class="header-anchor" href="#texto-da-nota" aria-label="Permalink to &quot;Texto da Nota&quot;">​</a></h3><p>Campo para escrever o conteúdo da nota. Suporta:</p><ul><li>Texto livre</li><li>Variáveis (<code>{{nome_variavel}}</code>)</li><li>Múltiplas linhas</li></ul><h3 id="fixar-mensagem" tabindex="-1">Fixar Mensagem <a class="header-anchor" href="#fixar-mensagem" aria-label="Permalink to &quot;Fixar Mensagem&quot;">​</a></h3><p>Quando ativado, a nota é fixada no topo do chat para fácil acesso.</p><h2 id="uso-de-variaveis" tabindex="-1">Uso de Variáveis <a class="header-anchor" href="#uso-de-variaveis" aria-label="Permalink to &quot;Uso de Variáveis&quot;">​</a></h2><p>Personalize as notas com variáveis:</p><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>⚠️ ATENÇÃO: Cliente VIP</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Dados coletados:</span></span>
<span class="line"><span>- Produto de interesse: {{produto_interesse}}</span></span>
<span class="line"><span>- Orçamento disponível: {{orcamento}}</span></span>
<span class="line"><span>- Prazo: {{prazo}}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="conexoes" tabindex="-1">Conexões <a class="header-anchor" href="#conexoes" aria-label="Permalink to &quot;Conexões&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Handle</th><th>Posição</th><th>Descrição</th></tr></thead><tbody><tr><td>Entrada</td><td>Esquerda</td><td>Recebe conexão do nó anterior</td></tr><tr><td>Saída</td><td>Direita</td><td>Continua para o próximo nó</td></tr></tbody></table><h2 id="exemplos-de-uso" tabindex="-1">Exemplos de Uso <a class="header-anchor" href="#exemplos-de-uso" aria-label="Permalink to &quot;Exemplos de Uso&quot;">​</a></h2><h3 id="resumo-para-atendente" tabindex="-1">Resumo para Atendente <a class="header-anchor" href="#resumo-para-atendente" aria-label="Permalink to &quot;Resumo para Atendente&quot;">​</a></h3><p>Quando transferir para atendimento humano:</p><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📋 RESUMO DO ATENDIMENTO</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Cliente: {{customer_name}}</span></span>
<span class="line"><span>Assunto: {{assunto}}</span></span>
<span class="line"><span>Problema: {{descricao_problema}}</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Tentativas já realizadas:</span></span>
<span class="line"><span>- Reiniciar aplicativo ❌</span></span>
<span class="line"><span>- Limpar cache ❌</span></span>
<span class="line"><span>- Atualizar versão ✅ (aguardando)</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Próximos passos sugeridos:</span></span>
<span class="line"><span>Verificar logs do servidor</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><h3 id="alerta-importante" tabindex="-1">Alerta Importante <a class="header-anchor" href="#alerta-importante" aria-label="Permalink to &quot;Alerta Importante&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🚨 CLIENTE COM RECLAMAÇÃO</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Este cliente já entrou em contato 3x sobre o mesmo problema.</span></span>
<span class="line"><span>Tratar com prioridade!</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Histórico:</span></span>
<span class="line"><span>{{historico_contatos}}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="dados-sensiveis" tabindex="-1">Dados Sensíveis <a class="header-anchor" href="#dados-sensiveis" aria-label="Permalink to &quot;Dados Sensíveis&quot;">​</a></h3><p>Para informações que o atendente precisa ver:</p><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>🔐 DADOS DE VERIFICAÇÃO</span></span>
<span class="line"><span></span></span>
<span class="line"><span>CPF informado: {{cpf}}</span></span>
<span class="line"><span>Último pedido: {{ultimo_pedido}}</span></span>
<span class="line"><span>Valor pendente: R$ {{valor_pendente}}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="instrucao-para-equipe" tabindex="-1">Instrução para Equipe <a class="header-anchor" href="#instrucao-para-equipe" aria-label="Permalink to &quot;Instrução para Equipe&quot;">​</a></h3><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>📌 INSTRUÇÕES</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Oferecer 10% de desconto se cliente demonstrar </span></span>
<span class="line"><span>interesse em cancelar.</span></span>
<span class="line"><span></span></span>
<span class="line"><span>Código do cupom: FIDELIDADE10</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="diferenca-nota-privada-vs-mensagem-do-sistema" tabindex="-1">Diferença: Nota Privada vs Mensagem do Sistema <a class="header-anchor" href="#diferenca-nota-privada-vs-mensagem-do-sistema" aria-label="Permalink to &quot;Diferença: Nota Privada vs Mensagem do Sistema&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Característica</th><th>Nota Privada</th><th>Mensagem do Sistema</th></tr></thead><tbody><tr><td>Aparece como nota</td><td>✅ Sim</td><td>❌ Não</td></tr><tr><td>Pode ser fixada</td><td>✅ Sim</td><td>❌ Não</td></tr><tr><td>Destaque visual</td><td>✅ Amarelo</td><td>Neutro</td></tr><tr><td>Uso principal</td><td>Anotações importantes</td><td>Logs e documentação</td></tr></tbody></table><h2 id="visualizacao" tabindex="-1">Visualização <a class="header-anchor" href="#visualizacao" aria-label="Permalink to &quot;Visualização&quot;">​</a></h2><p>A nota privada aparece:</p><ul><li>✅ Na timeline do atendimento (para atendentes)</li><li>✅ Com destaque visual (fundo amarelo)</li><li>✅ Fixada no topo (se configurado)</li><li>❌ <strong>NÃO</strong> é enviada ao cliente</li><li>❌ <strong>NÃO</strong> aparece no chat do cliente</li></ul><h2 id="boas-praticas" tabindex="-1">Boas Práticas <a class="header-anchor" href="#boas-praticas" aria-label="Permalink to &quot;Boas Práticas&quot;">​</a></h2><div class="tip custom-block"><p class="custom-block-title">Use para Informações Importantes</p><p>Reserve notas privadas para informações que o atendente precisa ver imediatamente.</p></div><div class="tip custom-block"><p class="custom-block-title">Fixe com Moderação</p><p>Fixe apenas notas realmente críticas para não poluir a visualização.</p></div><div class="tip custom-block"><p class="custom-block-title">Seja Claro</p><p>Escreva de forma clara e objetiva para que qualquer atendente entenda.</p></div><div class="tip custom-block"><p class="custom-block-title">Estruture a Informação</p><p>Use formatação (linhas, emojis, listas) para facilitar a leitura rápida.</p></div><h2 id="proximos-passos" tabindex="-1">Próximos Passos <a class="header-anchor" href="#proximos-passos" aria-label="Permalink to &quot;Próximos Passos&quot;">​</a></h2><ul><li><a href="/guide/flows/nodes/system-message">Nó: Mensagem do Sistema</a></li><li><a href="/guide/flows/nodes/update-customer">Nó: Atualizar Cliente</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("en/guide/flows/nodes/private-note.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const privateNote = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  privateNote as default
};
