import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Interflow Docs","description":"","frontmatter":{},"headers":[],"relativePath":"README.md","filePath":"README.md","lastUpdated":1766496965000}');
const _sfc_main = { name: "README.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="interflow-docs" tabindex="-1">Interflow Docs <a class="header-anchor" href="#interflow-docs" aria-label="Permalink to &quot;Interflow Docs&quot;">​</a></h1><p>📚 Documentação oficial da plataforma Interflow.</p><p>🌐 <strong>Site</strong>: <a href="https://docs.interflow.chat" target="_blank" rel="noreferrer">docs.interflow.chat</a></p><h2 id="sobre" tabindex="-1">Sobre <a class="header-anchor" href="#sobre" aria-label="Permalink to &quot;Sobre&quot;">​</a></h2><p>Este é o projeto de documentação pública da Interflow, uma plataforma de atendimento multicanal e CRM. A documentação é construída com <a href="https://vitepress.dev/" target="_blank" rel="noreferrer">VitePress</a> e suporta múltiplos idiomas.</p><h2 id="idiomas-suportados" tabindex="-1">Idiomas Suportados <a class="header-anchor" href="#idiomas-suportados" aria-label="Permalink to &quot;Idiomas Suportados&quot;">​</a></h2><ul><li>🇧🇷 <strong>Português (Brasil)</strong> - Idioma principal</li><li>🇺🇸 <strong>English</strong> - English version</li><li>🇪🇸 <strong>Español</strong> - Versión en español</li></ul><h2 id="desenvolvimento" tabindex="-1">Desenvolvimento <a class="header-anchor" href="#desenvolvimento" aria-label="Permalink to &quot;Desenvolvimento&quot;">​</a></h2><h3 id="requisitos" tabindex="-1">Requisitos <a class="header-anchor" href="#requisitos" aria-label="Permalink to &quot;Requisitos&quot;">​</a></h3><ul><li>Node.js 18+</li><li>npm ou yarn</li></ul><h3 id="instalacao" tabindex="-1">Instalação <a class="header-anchor" href="#instalacao" aria-label="Permalink to &quot;Instalação&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Clone o repositório</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">git</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> clone</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> https://github.com/rodrigooliver/interflow_docs.git</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> interflow_docs</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Instale as dependências</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h3 id="comandos" tabindex="-1">Comandos <a class="header-anchor" href="#comandos" aria-label="Permalink to &quot;Comandos&quot;">​</a></h3><div class="language-bash vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Iniciar servidor de desenvolvimento</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> dev</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Build para produção</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> build</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Preview do build</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> run</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> preview</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h3 id="servidor-de-desenvolvimento" tabindex="-1">Servidor de Desenvolvimento <a class="header-anchor" href="#servidor-de-desenvolvimento" aria-label="Permalink to &quot;Servidor de Desenvolvimento&quot;">​</a></h3><p>O servidor será iniciado em <code>http://localhost:5173</code>.</p><h2 id="estrutura-do-projeto" tabindex="-1">Estrutura do Projeto <a class="header-anchor" href="#estrutura-do-projeto" aria-label="Permalink to &quot;Estrutura do Projeto&quot;">​</a></h2><div class="language- vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>interflow_docs/</span></span>
<span class="line"><span>├── .vitepress/</span></span>
<span class="line"><span>│   └── config.mts          # Configuração do VitePress</span></span>
<span class="line"><span>├── public/</span></span>
<span class="line"><span>│   ├── logo.svg            # Logo do site</span></span>
<span class="line"><span>│   ├── hero-image.svg      # Imagem da home</span></span>
<span class="line"><span>│   └── images/             # Imagens da documentação</span></span>
<span class="line"><span>├── guia/                   # Guias em português</span></span>
<span class="line"><span>│   ├── introducao.md</span></span>
<span class="line"><span>│   ├── inicio-rapido.md</span></span>
<span class="line"><span>│   ├── canais/</span></span>
<span class="line"><span>│   ├── chat/</span></span>
<span class="line"><span>│   ├── fluxos/</span></span>
<span class="line"><span>│   ├── crm/</span></span>
<span class="line"><span>│   └── ...</span></span>
<span class="line"><span>├── api/                    # Documentação da API (PT)</span></span>
<span class="line"><span>├── recursos/               # Recursos (PT)</span></span>
<span class="line"><span>├── en/                     # Versão em inglês</span></span>
<span class="line"><span>│   ├── guide/</span></span>
<span class="line"><span>│   ├── api/</span></span>
<span class="line"><span>│   └── ...</span></span>
<span class="line"><span>├── es/                     # Versão em espanhol</span></span>
<span class="line"><span>│   ├── guia/</span></span>
<span class="line"><span>│   ├── api/</span></span>
<span class="line"><span>│   └── ...</span></span>
<span class="line"><span>├── index.md                # Página inicial (PT)</span></span>
<span class="line"><span>├── changelog.md            # Histórico de versões</span></span>
<span class="line"><span>├── package.json</span></span>
<span class="line"><span>└── README.md</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br></div></div><h2 id="contribuindo" tabindex="-1">Contribuindo <a class="header-anchor" href="#contribuindo" aria-label="Permalink to &quot;Contribuindo&quot;">​</a></h2><h3 id="adicionando-conteudo" tabindex="-1">Adicionando Conteúdo <a class="header-anchor" href="#adicionando-conteudo" aria-label="Permalink to &quot;Adicionando Conteúdo&quot;">​</a></h3><ol><li>Crie ou edite arquivos <code>.md</code> na pasta correspondente</li><li>Use Markdown padrão com extensões VitePress</li><li>Adicione imagens em <code>public/images/</code></li><li>Atualize a sidebar em <code>.vitepress/config.mts</code> se necessário</li></ol><h3 id="padroes-de-conteudo" tabindex="-1">Padrões de Conteúdo <a class="header-anchor" href="#padroes-de-conteudo" aria-label="Permalink to &quot;Padrões de Conteúdo&quot;">​</a></h3><ul><li>Use o aviso de &quot;Em Atualização&quot; no início de páginas incompletas</li><li>Inclua placeholders para screenshots e vídeos</li><li>Mantenha consistência entre os idiomas</li><li>Use tabelas para informações estruturadas</li><li>Inclua exemplos de código quando relevante</li></ul><h3 id="exemplo-de-placeholder" tabindex="-1">Exemplo de Placeholder <a class="header-anchor" href="#exemplo-de-placeholder" aria-label="Permalink to &quot;Exemplo de Placeholder&quot;">​</a></h3><div class="language-markdown vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">&lt;!-- Placeholder para screenshot --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;div style=&quot;background: #f5f5f5; border: 2px dashed #ccc; ...&quot;&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  &lt;span&gt;📸&lt;/span&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  &lt;p&gt;Screenshot: Descrição&lt;/p&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&lt;/div&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="bloco-de-aviso" tabindex="-1">Bloco de Aviso <a class="header-anchor" href="#bloco-de-aviso" aria-label="Permalink to &quot;Bloco de Aviso&quot;">​</a></h3><div class="language-markdown vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">::: warning EM ATUALIZAÇÃO</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">Esta documentação está em fase de atualização contínua.</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:::</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h2 id="deploy" tabindex="-1">Deploy <a class="header-anchor" href="#deploy" aria-label="Permalink to &quot;Deploy&quot;">​</a></h2><p>A documentação é automaticamente deployada quando há push para a branch <code>main</code>.</p><p><strong>Plataformas suportadas:</strong></p><ul><li>Vercel</li><li>Netlify</li><li>GitHub Pages</li><li>Cloudflare Pages</li></ul><h3 id="variaveis-de-ambiente" tabindex="-1">Variáveis de Ambiente <a class="header-anchor" href="#variaveis-de-ambiente" aria-label="Permalink to &quot;Variáveis de Ambiente&quot;">​</a></h3><div class="language-env vp-adaptive-theme line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">env</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>DOCS_URL=https://docs.interflow.chat</span></span>
<span class="line"><span>NODE_ENV=production</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="tecnologias" tabindex="-1">Tecnologias <a class="header-anchor" href="#tecnologias" aria-label="Permalink to &quot;Tecnologias&quot;">​</a></h2><ul><li><a href="https://vitepress.dev/" target="_blank" rel="noreferrer">VitePress</a> - Framework de documentação</li><li><a href="https://vuejs.org/" target="_blank" rel="noreferrer">Vue 3</a> - Framework reativo</li><li><a href="https://commonmark.org/" target="_blank" rel="noreferrer">Markdown</a> - Formato de conteúdo</li></ul><h2 id="licenca" tabindex="-1">Licença <a class="header-anchor" href="#licenca" aria-label="Permalink to &quot;Licença&quot;">​</a></h2><p>Copyright © 2024-presente Interflow. Todos os direitos reservados.</p><hr><p>🔗 <strong>Links Úteis</strong></p><ul><li><a href="https://app.interflow.chat" target="_blank" rel="noreferrer">Plataforma Interflow</a></li><li><a href="https://interflow.chat" target="_blank" rel="noreferrer">Site Institucional</a></li><li><a href="https://docs.interflow.chat/api/" target="_blank" rel="noreferrer">API Reference</a></li><li><a href="https://github.com/rodrigooliver/interflow" target="_blank" rel="noreferrer">GitHub</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("README.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const README = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  README as default
};
